- src/CMakeLists.txt
a try for fixing recent "Update SHA" problem in nupic. 
please merge https://github.com/numenta/nupic/pull/1690 first.
Fixes numenta/nupic#1694
> try saner settings for GCC to fix travis failure?

- src/CMakeLists.txt
Please try #294 first
Fixes https://github.com/numenta/nupic.core/issues/296 (hopefully, cannot reproduce locally)
> disable temp. optimization flags

- .travis.yml
Broken in https://github.com/numenta/nupic.core/pull/298.
Fixes #303.
> Fixing broken deploy condition

- src/nupic/algorithms/FlatSpatialPooler.cpp
- src/nupic/algorithms/FlatSpatialPooler.hpp
- src/nupic/algorithms/SpatialPooler.cpp
- src/nupic/algorithms/SpatialPooler.hpp
> Mark a bunch of SP functions const

- src/CMakeLists.txt
> Windows build: Updated cmake

- external/common/include/cycle_counter.hpp
- external/common/include/zconf.h
- src/examples/prototest.cpp
- src/nupic/algorithms/ImageSensorLite.cpp
- src/nupic/engine/RegionImplFactory.cpp
- src/nupic/math/ArrayAlgo.hpp
- src/nupic/math/SparseBinaryMatrix.hpp
- src/nupic/math/SparseMatrix.hpp
- src/nupic/math/Utils.hpp
- src/nupic/ntypes/Buffer.cpp
- src/nupic/os/Directory.cpp
- src/nupic/os/DynamicLibrary.cpp
- src/nupic/os/Env.cpp
- src/nupic/os/FStream.cpp
- src/nupic/os/FStream.hpp
- src/nupic/os/OSUnix.cpp
- src/nupic/os/Path.cpp
- src/nupic/os/Regex.cpp
- src/nupic/os/Timer.cpp
- src/nupic/types/Fraction.cpp
- src/nupic/types/Types.h
- src/nupic/utils/LoggingException.cpp
- src/test/unit/UnitTestMain.cpp
- src/test/unit/algorithms/FlatSpatialPoolerTest.cpp
- src/test/unit/algorithms/SpatialPoolerTest.cpp
- src/test/unit/os/OSTest.cpp
- src/test/unit/utils/RandomTest.cpp
Fixes #309
Depends https://github.com/numenta/nupic.core/pull/313
**Very important:**
This PR depends of https://github.com/numenta/nupic.core/pull/313, once the latter one is merged then this PR should be reviewed.
Notes:
- `<sys/time.h>` was replaced by `<nupic/os/Timer.hpp>`. `<sys/time.h>` doesn't exist in Windows, and `<nupic/os/Timer.hpp>` is the default Nupic class to handle this job.
> Windows build: Update source files to build under Windows

- Package.nuspec
- README.md
- appveyor.yml
Fixes #311.
This PR aims check whether AppVeyor build is green.
> Windows build: Assure appveyor is green

- src/nupic/types/Types.h
> Fix bug with Windows types

- src/nupic/algorithms/FDRCSpatial.hpp
- src/nupic/algorithms/FDRSpatial.hpp
Fixes https://github.com/numenta/nupic.core/issues/390
> Revert "Remove obsolete implementations of SP"

- README.md
- external/windows64/README.md
> 368 document Windows development

- appveyor.yml
> AppVeyor config shallow_clone: false

- src/CMakeLists.txt
- src/nupic/algorithms/Connections.cpp
- src/nupic/algorithms/Connections.hpp
- src/nupic/proto/ConnectionsProto.capnp
- src/test/unit/algorithms/ConnectionsTest.cpp
- src/test/unit/algorithms/ConnectionsTest.hpp
Fixes https://github.com/numenta/nupic.core/issues/422.
> Implement serialization of Connections

- src/CMakeLists.txt
- src/nupic/proto/TemporalMemoryProto.capnp
Fixes https://github.com/numenta/nupic.core/issues/418.
> Add Temporal Memory serialization schema

- .travis.yml
> Remove travis webhook registration

- src/nupic/proto/TemporalMemoryV1.capnp
Fixes https://github.com/numenta/nupic.core/issues/435
> Add schema to TP

- src/CMakeLists.txt
- src/nupic/proto/LinkProto.capnp
> Fixes #442 - Adds LinkProto capnp serialization.

- src/CMakeLists.txt
- src/nupic/proto/RegionProto.capnp
> Fixes #443 - Adds RegionProto capnp serialization.

- src/CMakeLists.txt
- src/nupic/proto/TestNodeProto.capnp
> Fixes #445 - Adds TestNodeProto capnp schema.

- src/CMakeLists.txt
- src/nupic/proto/VectorFileSensorProto.capnp
> Fixes #446 - Adds VectorFileSensorProto capnp schema.

- src/nupic/engine/Link.cpp
- src/nupic/engine/Link.hpp
> Fixes #447 - Adds capnp serialization to Link class.

- src/nupic/algorithms/SpatialPooler.cpp
- src/nupic/algorithms/SpatialPooler.hpp
- src/test/unit/algorithms/SpatialPoolerTest.cpp
Fixes: https://github.com/numenta/nupic.core/issues/460
@subutai @scottpurdy 
(A corresponding change in the Python will be made in another PR in the nupic repo.)
> Fixing potential SP initialization issue

- src/nupic/engine/TestNode.cpp
- src/nupic/engine/TestNode.hpp
> Fixes #450 - Adds TestNode capnp serialization.

- src/nupic/proto/TemporalMemoryProto.capnp
> Update Temoral Memory Proto to include Orphan Decay

- src/nupic/regions/VectorFileEffector.cpp
- src/nupic/regions/VectorFileEffector.hpp
> Fixes #459 - Adds VectorFileEffector capnp serialization.

- src/nupic/regions/VectorFileSensor.cpp
- src/nupic/regions/VectorFileSensor.hpp
> Fixes #451 - Adds VectorFileSensor capnp serialization.

- src/nupic/regions/VectorFileSensor.cpp
- src/nupic/regions/VectorFileSensor.hpp
> Adds capnp constructor for VectorFileSensor.

- src/nupic/regions/VectorFileEffector.cpp
- src/nupic/regions/VectorFileEffector.hpp
> Adds capnp constructor to VectorFileEffector.

- src/nupic/engine/Region.cpp
- src/nupic/engine/Region.hpp
fixes #448 
@chetan51 please fix
> Implements capnp serialization in Region

- src/examples/algorithms/HelloSP_TP.cpp
- src/examples/prototest.cpp
- src/nupic/algorithms/SpatialPooler.cpp
- src/nupic/algorithms/SpatialPooler.hpp
Fixes #174
@scottpurdy Please review
> Removed stripNeverLearned from SP.compute and updated comments

- src/nupic/algorithms/Connections.cpp
- src/nupic/algorithms/Connections.hpp
- src/nupic/proto/ConnectionsProto.capnp
- src/test/unit/algorithms/ConnectionsTest.cpp
Fixes https://github.com/numenta/nupic.core/issues/499.
> Allow specifying max number of synapses per segment

- src/nupic/algorithms/Cells4.cpp
> making sure cells are sorted before set_difference

- .travis.yml
- appveyor-scripts/install_python_pip.ps1
- appveyor.yml
- external/common/requirements.txt
- src/CMakeLists.txt
Modified the installation of numpy for appveyor and travis to 1.9.2.  Also added a requirements.txt file that can be read by nupic so they have the same version of numpy.
@rhyolight
For numenta.nupic/#1516
Fixes #518.
> Upgraded numpy to 1.9.2

- src/nupic/regions/PyRegion.cpp
Fixes #520 
@scottpurdy please review
> Optional constraints parameter in PyRegion

- src/nupic/algorithms/TemporalMemory.cpp
> TM constructor parameter checks

- src/nupic/algorithms/TemporalMemory.cpp
- src/nupic/algorithms/TemporalMemory.hpp
- src/test/unit/algorithms/TemporalMemoryTest.cpp
- src/test/unit/algorithms/TemporalMemoryTest.hpp
> Adding synapse orphan decay

- src/CMakeLists.txt
> Define expected CMake policy behaviour

- bindings/py/setup.py
@akhilaananthram - This alright?
fixes #531
> Change Python package name to nupic.bindings (from nupiccore).

- src/test/unit/algorithms/TemporalMemoryTest.cpp
Reverts numenta/nupic.core#523
This PR ended up breaking the build due to a conflict with changes merged since Travis marked it as green.
> Revert "TM unit test completion"

- src/nupic/algorithms/Connections.cpp
- src/nupic/algorithms/Connections.hpp
- src/nupic/proto/ConnectionsProto.capnp
- src/test/unit/algorithms/ConnectionsTest.cpp
- src/test/unit/algorithms/ConnectionsTest.hpp
> Connections load and save

- bindings/py/nupic/bindings/regions/PyRegion.py
- bindings/py/nupic/bindings/regions/TestNode.py
- bindings/py/nupic/bindings/regions/__init__.py
- bindings/py/nupic/bindings/tests/__init__.py
- bindings/py/nupic/bindings/tests/pyregion_test.py
> Moves PyRegion and TestNode over from nupic with tests.

- bindings/py/setup.py
> Updated to correct pypi license string.

- ci/travis/after_success-release-linux.sh
- ci/travis/after_success-release-osx.sh
Update the scripts with the correct paths
@rhyolight
> Update after release scripts for nupic.bindings

- bindings/py/setup.py
Updated nupic.bindings to 0.1.1
@rhyolight
> updated version of nupic.bindings

- bindings/py/nupic/bindings/regions/PyRegion.py
> Remove unused import

- README.md
> Updated Readme to describe installation of nupic.bindings

- README.md
fixes #574 
@rhyolight or @oxtopus - please review
I am going to merge without waiting for review since I need these changes in to get things moving (and it is documentation changes only). But please do post-merge review.
> Documentation updates to reflect recent changes.

- bindings/py/setup.py
fixes #577 
@breznak - does this fix the issue for you?
> Get qualified path to requirements.txt

- ci/travis/before_install-linux.sh
- ci/travis/before_install-osx.sh
> Force static build of capnp

- README.md
- external/README.md
> Add back more explicit Cap'n Proto build instructions.

- src/CMakeLists.txt
> Adds installation of capnp libraries and headers to cmake build.

- bindings/py/setup.py
- src/CMakeLists.txt
> Revert removal of capnpc, which appears to be needed after all.

- src/nupic/math/SparseBinaryMatrix.hpp
- src/nupic/math/SparseMatrix.hpp
Fixes #606
- Removed useless //----... comments
- Ran `clang-format -i` to fixup indentation
No functional changes.
> Code cleanup of Sparse*Matrix.hpp files

- .clang-format
> Add .clang-format file from standard `clang-format -dump-config`

- ci/travis/after_success-release-linux.sh
> Disable uploading of source tarball to pypi.  It doesn't work.

- bindings/py/requirements.txt
Fixes https://github.com/numenta/nupic/issues/2607
> Explicit numpy 1.9.2 version.

- src/nupic/py_support/PyHelpers.cpp
- src/nupic/py_support/PyHelpers.hpp
Fixes https://github.com/numenta/nupic.core/issues/658.
> Mark py::Instance.invoke as const

- bindings/py/nupic/bindings/algorithms.i
Fixes https://github.com/numenta/nupic.core/issues/686.
> Propagate maxSegmentsPerCell and maxSynapsesPerSegment settings from OPF model params to Connections

- bindings/py/requirements.txt
> Revert back to numpy==1.9.2

- src/nupic/utils/Random.cpp
- src/test/unit/utils/RandomTest.cpp
> Adds unit tests for getUInt64 and getReal64.

- bindings/py/nupic/bindings/algorithms.i
- src/nupic/algorithms/SpatialPooler.cpp
Fixes https://github.com/numenta/nupic.core/issues/688.
> Make python SP and C++ SP compatible

- src/CMakeLists.txt
@oxtopus please review (debug print change only)
> Add debugging statement for cmake.

- src/nupic/algorithms/BitHistory.hpp
- src/nupic/algorithms/Connections.cpp
- src/nupic/algorithms/Connections.hpp
- src/nupic/algorithms/FastClaClassifier.cpp
- src/nupic/algorithms/FastClaClassifier.hpp
- src/nupic/algorithms/SpatialPooler.cpp
- src/nupic/algorithms/SpatialPooler.hpp
- src/nupic/algorithms/TemporalMemory.cpp
- src/nupic/algorithms/TemporalMemory.hpp
- src/nupic/base/Serializable.hpp
- src/nupic/engine/Link.hpp
- src/nupic/engine/Network.cpp
- src/nupic/engine/Network.hpp
- src/nupic/engine/Region.hpp
- src/nupic/engine/RegionImpl.cpp
- src/nupic/engine/RegionImpl.hpp
- src/nupic/engine/TestNode.hpp
- src/nupic/math/SparseBinaryMatrix.hpp
- src/nupic/math/SparseMatrix.hpp
- src/nupic/regions/PyRegion.hpp
- src/nupic/regions/VectorFileEffector.hpp
- src/nupic/regions/VectorFileSensor.hpp
- src/nupic/types/Serializable.hpp
- src/nupic/utils/Random.cpp
- src/nupic/utils/Random.hpp
Fixes https://github.com/numenta/nupic.core/issues/708.
> Move repeated read / write logic to base Serializable class

- README.md
- appveyor.yml
- ci/travis/after_success-release-linux.sh
- ci/travis/after_success-release-osx.sh
- ci/travis/before_deploy.sh
Updates CI and README to reflect new build steps after #664 and #713 
@oxtopus 
Merging pre-review to get build green. The previous PRs passed Travis PR but failed in the after-merge code.
> Update references to --nupic-core-dir and switch to new build method.

- src/nupic/algorithms/BitHistory.hpp
- src/nupic/algorithms/Connections.hpp
- src/nupic/algorithms/FastClaClassifier.hpp
- src/nupic/algorithms/TemporalMemory.hpp
- src/nupic/engine/Link.hpp
- src/nupic/engine/Network.hpp
- src/nupic/engine/Region.hpp
- src/nupic/engine/RegionImpl.hpp
- src/nupic/math/SparseBinaryMatrix.hpp
- src/nupic/math/SparseMatrix.hpp
- src/nupic/utils/Random.hpp
Fixes https://github.com/numenta/nupic.core/issues/726.
> Specify public when inheriting from Serializable

- .travis.yml
Fixes https://github.com/numenta/nupic.core/issues/750.
> Point travis to correct py bindings tests

- bindings/py/nupic/bindings/regions/PyRegion.py
- bindings/py/nupic/bindings/regions/TestNode.py
- src/nupic/regions/PyRegion.cpp
Fixes https://github.com/numenta/nupic.core/issues/746.
> Make PyRegion read a classmethod

- Dockerfile
Fixes #742 
@scottpurdy this has been a long-time coming.
> Add Dockerfile for building nupic.core from source

- Doxyfile
> Added version to doxyfile.

- bindings/py/nupic/bindings/check.py
- bindings/py/setup.py
- bindings/py/tests/check_test.py
- bindings/py/tests/load_bindings_test.py
Fixes #698 
Not sure of the best place to update documentation to reflect this change.
@scottpurdy
> Create bindings load check script and unit test

- README.md
depends on #715 
fixes #763
@oxtopus and @rhyolight please review
> Updates README to accurately capture build options.

- src/nupic/bindings/algorithms.i
Fixes https://github.com/numenta/nupic.core/issues/782.
> Add bindings for CLAClassifier serialization

- src/nupic/algorithms/SpatialPooler.cpp
Fixes https://github.com/numenta/nupic.core/issues/780.
> Fix SpatialPooler read

- appveyor.yml
> Running tagged builds in AV.

- appveyor.yml
> Fixing twine upload of windows binary.

- src/nupic/proto/BitHistory.capnp
- src/nupic/proto/ClaClassifier.capnp
Fixes https://github.com/numenta/nupic.core/issues/790.
> Fix: FastCLAClassifier serialization is producing inconsistent results

- src/nupic/ntypes/NodeSet.hpp
> Added include of Log.hpp in NodeSet.hpp

- bindings/py/nupic/bindings/regions/PyRegion.py
- src/nupic/bindings/algorithms.i
Fixes https://github.com/numenta/nupic.core/issues/796.
Builds on https://github.com/numenta/nupic.core/issues/793.
> Refactor PyRegion subclasses to take specific proto object in read

- src/nupic/bindings/algorithms.i
- src/nupic/bindings/engine_internal.i
Fixes https://github.com/numenta/nupic.core/issues/793.
> Update SWIG bindings of SpatialPooler, TemporalMemory, CLAClassifier to add read class methods to C++ classes

- src/CMakeLists.txt
- src/nupic/algorithms/Segment.cpp
- src/test/unit/algorithms/SegmentTest.cpp
Fixes #820 
Also adds unit test for freeNSynapses that confirms desired behavior.
> Fixes freeNSynapses deletes arbitrary synapses

- src/nupic/algorithms/Connections.cpp
- src/nupic/algorithms/Connections.hpp
- src/test/unit/algorithms/ConnectionsTest.cpp
Fixes #827 
@subutai @scottpurdy @chetan51
> Destroy lowest permanence synapse when synapse limit is reached

- src/nupic/bindings/algorithms.i
Fixes https://github.com/numenta/nupic.core/issues/830.
> Update bindings for C++ Connections to expose 'read' class method

- src/nupic/bindings/algorithms.i
Fixes https://github.com/numenta/nupic.core/issues/828.
> Updating bindings for TemporalMemory to work with tests in nupic

- src/nupic/regions/PyRegion.cpp
> Remove annoying debug print statement

- src/nupic/algorithms/TemporalMemory.cpp
- src/nupic/algorithms/TemporalMemory.hpp
- src/nupic/bindings/algorithms.i
> TM: Add accessor methods and update API to use lists of indices

- src/nupic/algorithms/TemporalMemory.cpp
- src/nupic/bindings/algorithms.i
Fixes https://github.com/numenta/nupic.core/issues/836.
> Make C++ TM and python TM produce identical results

- Dockerfile
> Fixup url to get pip

- src/nupic/algorithms/TemporalMemory.cpp
- src/nupic/algorithms/TemporalMemory.hpp
- src/nupic/bindings/algorithms.i
> Change TM init parameters to accept segment and synapse limit.

- src/nupic/algorithms/Connections.cpp
Fixes https://github.com/numenta/nupic.core/issues/847.
> Fix: Incompatibility in Connections.computeActivity with python

- src/nupic/algorithms/TemporalMemory.cpp
- src/nupic/algorithms/TemporalMemory.hpp
- src/nupic/bindings/algorithms.i
- src/test/unit/algorithms/TemporalMemoryTest.cpp
> Add accessors for TM columnForCell and cellsForColumn

- bindings/py/tests/temporal_memory_test.py
Fixes #807
This passes for me, and I cannot reproduce the original reported behavior.
> Add test to exercise code snippet known to cause segfault

- ci/bamboo/build-linux.sh
Fixes #859.
This installs dependencies and builds the nupic.bindings python package(s).
> Entry point for building linux in Bamboo CI environment

- ci/travis/after_success-release-linux.sh
- ci/travis/after_success-release-osx.sh
- ci/travis/before_deploy.sh
- ci/travis/before_install-linux.sh
- ci/travis/before_install-osx.sh
> Installing wheel 0.25.0

- src/examples/regions/HelloRegions.cpp
> Fixed path of Data.csv used by HelloRegions.cpp test

- src/nupic/algorithms/Connections.cpp
> Fix clang build error that shows up in travis-ci

- appveyor.yml
> Use mingwpy from bitbucket.org/carlkl/mingw-w64-for-python to fix broken win64 build

- src/CMakeLists.txt
- src/nupic/proto/SdrClassifier.capnp
@scottpurdy 
Add proto for the new SDR classifier
> Add Proto for SDR Classifier

- src/nupic/algorithms/Connections.cpp
- src/test/unit/algorithms/ConnectionsTest.cpp
> Bugfix: Keep the destroyed synapses count in sync.

- external/Swig.cmake
> Update cmake variable names to be better.

- ci/bamboo/build-linux-debug.sh
- src/CMakeLists.txt
follow up to #951 
@vitaly-krugl please review
> Update iwyu docs and add to Bamboo

- DEPENDENCIES.md
Added terminating newline to DEPENDENCIES.md to grigger build for helping to debug http://help.appveyor.com/discussions/problems/4490-undesired-rebuilding-of-all-open-prs-after-a-merge-into-master
> Trigger build to help debug AppVeyor rebuilding of other PRs

- appveyor.yml
To help diagnose http://help.appveyor.com/discussions/problems/4490-undesired-rebuilding-of-all-open-prs-after-a-merge-into-master/comments
> Echo appveyor build vars for diagnostics

- external/common/include/CSV_README.md
- external/common/include/csv.h
to externals, it's a simple (C++11) header file
Fixes #904
> add CSV parser library

- .travis.yml
Fixes #560 as per https://github.com/numenta/nupic.core/issues/560#issuecomment-213389037  .
> Filter "-- Installing:" from make output

- src/nupic/algorithms/SpatialPooler.cpp
- src/nupic/algorithms/SpatialPooler.hpp
- src/nupic/bindings/algorithms.i
- src/test/unit/algorithms/SpatialPoolerTest.cpp
Fixes #974 
@subutai @hernandezurbina
> Add overlap accessors to SpatialPooler

- Dockerfile
- README.md
- bindings/py/setup.py
- ci/bamboo/build-linux-debug.sh
- ci/bamboo/build-linux-release.sh
- ci/travis/before_install-linux.sh
- ci/travis/before_install-osx.sh
@natoromano fyi
@vitaly-krugl - please review
> Updates pycapnp to 0.5.8.

- ci/bamboo/build-linux-debug.sh
- ci/bamboo/build-linux-release.sh
> Save python test results and report on coverage.

- ci/bamboo/build-linux-debug.sh
- ci/bamboo/build-linux-release.sh
> Fix Bamboo variable access.

- src/CMakeLists.txt
- src/nupic/algorithms/SDRClassifier.cpp
- src/nupic/algorithms/SDRClassifier.hpp
- src/nupic/proto/SdrClassifier.capnp
- src/test/unit/algorithms/SDRClassifierTest.cpp
Fixes numenta/nupic#3055.
C++ implementation of the new SDRClassifier. It ports [the Python implementation ](https://github.com/numenta/nupic/blob/master/src/nupic/algorithms/sdr_classifier.py) to a faster C++ version.
@scottpurdy
> First C++ implementation of SDRClassifier

- src/nupic/algorithms/TemporalMemory.cpp
- src/test/unit/algorithms/TemporalMemoryTest.cpp
Fixes #1021 
Thanks @andrewmalta13 for catching this.
> Fix an unsigned int underflow bug

- src/nupic/bindings/experimental.i
- src/nupic/experimental/ExtendedTemporalMemory.cpp
- src/nupic/experimental/ExtendedTemporalMemory.hpp
- src/nupic/experimental/README.md
- src/test/unit/experimental/ExtendedTemporalMemoryTest.cpp
Fixes #1044
The C++ ETM now passes all of the [extensive_etm_test](https://github.com/numenta/nupic.research/blob/85522c3c15146f7f64fb8348c8f26034612197f2/tests/extended_temporal_memory/extensive_etm_test.py)s.
> Implement learnOnOneCell in the ETM

- CMakeLists.txt
- ci/bamboo/build-windows.ps1
- src/CMakeLists.txt
- src/nupic/engine/RegionImplFactory.cpp
- src/nupic/regions/PyRegion.cpp
- src/nupic/utils/LogItem.cpp
Fixes #1078
Note that we're proceeding despite the failure of py_region_test.exe, since it also fails on our AppVeyor build; I commented it out in this PR (it was omitted in AppVeyor build); see issue #1075
> DEVOPS-157 Integrate win64 release build into Bamboo-CI

- RELEASE.md
Knowing this will likely change, but this is a good base. Fixes #1087.
> Added same release doc as in NuPIC.

- ci/bamboo/build-osx.sh
fixes #1093 
@oxtopus  please review  and let me know if I am misunderstanding the point of these flags.
> Remove cache-related logic that isn't applicable in Vagrant environment.

- src/nupic/regions/PyRegion.cpp
- src/test/integration/PyRegionTest.cpp
> Network API: allow Bools to be used as creation params

- src/nupic/engine/Input.cpp
- src/nupic/engine/RegionImplFactory.cpp
- src/nupic/regions/PyRegion.cpp
Self-explanatory.
@mrcslws please review
> Better exceptions when there are errors loading regions.

- src/nupic/algorithms/SpatialPooler.cpp
- src/test/unit/algorithms/SpatialPoolerTest.cpp
C++ counterpart to https://github.com/numenta/nupic/pull/3361
cc @ywcui1990 
Fixes #1100
> Obey wrapAround paramater for columns, not just inputs

- src/test/unit/algorithms/TemporalMemoryTest.cpp
Fixes #1102
/cc @scottpurdy. I used this to test https://github.com/numenta/nupic.core/pull/1071 before merging it.
> Manual TM serialization backward-compatibility test code

- ci/bamboo/build-osx.sh
- ci/build-and-test-nupic-bindings.sh
Also ignoring installed for pip bindings dependencies.
> DEVOPS-181: Added --user option to build script.

- ci/build-and-test-nupic-bindings.sh
Attempt to fix intermittent pip install timeouts.
> DEVOPS-212: pip install timeouts

- .travis.yml
- ci/travis/before_install-linux.sh
> pip install with optional --user flag via env var.

- ci/bamboo/build-osx.sh
- ci/build-and-test-nupic-bindings.sh
fixes #1121
I didn't realize this stuff got into master.
> Removed artifacts of old solution.

- .travis.yml
- ci/travis/after_success-release-linux.sh
- ci/travis/before_install-linux.sh
Fixes #1126 
Attempted so far:
- Restored travis-related configuration to state of last-passing travis build
- Removed linux
- Added osx_image
> Investigating OS X Travis builds

- ci/bamboo/fetch_remote.py
@rhyolight please review
This will be used in Bamboo to check status and fetch artifacts from Travis and AppVeyor.
> Adds script for fetching artifacts from Travis or AppVeyor.

- src/nupic/engine/Region.cpp
> Initialize timer variable in 'Regioncpp' file

- README.md
- bindings/py/requirements.txt
- ci/appveyor/install_python_pip.ps1
- external/windows32-gcc/README.md
- external/windows64-gcc/README.md
- external/windows64/README.md
> Update numpy to 1.11.2

- ci/bamboo/fetch_remote.py
This addresses https://jira.numenta.com/browse/DEVOPS-231
> Updated to match new CI service JSON structure

- Doxyfile
- README.md
fixes #1149 
@rhyolight please review
> Use VERSION file when generating docs.

- RELEASE.md
> Updated release docs to include Github release creation.

- src/nupic/algorithms/SpatialPooler.cpp
> Make the boost factor rounding mimic numpy's rounding

- src/nupic/engine/Input.cpp
- src/nupic/engine/Input.hpp
- src/nupic/engine/Link.cpp
- src/nupic/engine/Link.hpp
- src/nupic/engine/LinkPolicy.hpp
- src/nupic/engine/Network.cpp
- src/nupic/engine/Network.hpp
- src/nupic/engine/Output.cpp
- src/nupic/engine/UniformLinkPolicy.cpp
- src/nupic/engine/UniformLinkPolicy.hpp
- src/test/unit/engine/InputTest.cpp
@scottpurdy  - this is the implementation sans serialization support.
Per offline discussions with Scott P.:
1. Serialization support to be implemented via follow-on PR.
2. nupic's CLAModel class will not support delayed links.
> NUP-2306 delayed links sans serialization support

- bindings/py/tests/sparse_matrix_test.py
- src/nupic/bindings/sparse_matrix.i
- src/nupic/math/SparseMatrix.hpp
- src/test/unit/math/SparseMatrixUnitTest.cpp
Fixes #1188
See the issue for an explanation.
> SparseMatrix: setRandomZerosOnOuter with list of counts

- bindings/py/tests/sparse_matrix_test.py
- src/nupic/bindings/sparse_matrix.i
- src/nupic/math/SparseMatrix.hpp
> SparseMatrix: Add option to specify rows in nNonZerosPerRow

- bindings/py/nupic/bindings/__init__.py
> Drop the declare_namespace call - Issue #1072

- RELEASE.md
> Added missing steps in RELEASE.md based on my release experience today.

- src/nupic/engine/Input.cpp
@vitaly-krugl please review
cc @subutai @mrcslws 
fixes #1212
> Fix bug with region dimensions inference in network API. fixes #1212

- circle.yml
@oxtopus - I messed it up 😭 
I'm just going to merge since this doesn't affect normal builds.
> Fix file existence check for virtualenv.

- circle.yml
> Please finally work.

- src/nupic/algorithms/Cells4.cpp
> NUP-2324 Improved explanation of containers in Cells4::adaptSegment implementation

- CHANGELOG.md
> corrected typo in CHANGELOG.md (boostingStrength -> boostStrength)

- .travis.yml
- docs/xunit.xslt
> Fixing travis-ci unit tests

- ci/bamboo/fetch_remote.py
> Fix up fetch_remote script to properly poll until the build is complete.

- src/nupic/bindings/algorithms.i
- src/nupic/bindings/engine_internal.i
I'm having trouble getting rid of the serializable warnings in #1253 so am using this PR to get the simpler changes merged.
> Fix up some out of date SWIG interface code

- src/nupic/engine/NuPIC.cpp
> Remove comments from NuPIC.cpp

- bindings/py/tests/sparse_matrix_test.py
- src/nupic/bindings/sparse_matrix.i
- src/nupic/math/SparseMatrix.hpp
> Add a nNonZerosPerRowOnCols SparseMatrix method

- src/CMakeLists.txt
> Eliminate installation of unnecessary header files when building nupic.bindings

- .travis.yml
- src/CMakeLists.txt
Fixes #1272
Please fast-track the code review to get master build back to green.
cc @oxtopus
> Install Version.hpp unconditionally for the sake of the deployment usage in .travis.yaml

- bindings/py/requirements.txt
> bump pytest-* dependencies to latest version

- src/nupic/py_support/PyHelpers.cpp
- src/test/unit/py_support/PyHelpersTest.cpp
> Bool PyObject* constructor should assume INCREF already happened

- README.md
- src/CMakeLists.txt
@scottpurdy Please review
fixes #1271
> NUP-2395 Add documentation for IWYU

- bindings/py/src/nupic/bindings/regions/PyRegion.py
> Added PyRegion RST docstrings

- circle.yml
Display clear failure message if Circle build is attempted on Linux
@scottpurdy Please review
> DEVOPS-291 Integrate Circle

- README.md
- bindings/py/requirements.txt
- ci/appveyor/install_python_pip.ps1
> Bump dependency numpy==1.12.1

- circle.yml
Change to uploading on any build not on a fork, including pull requests.  
Circle's behavior on PRs from forks was tested using a second Github account, and it behaves properly.
@scottpurdy Please review
> DEVOPS-342 Upload PR artifacts to S3

- src/nupic/algorithms/Connections.cpp
- src/nupic/algorithms/Connections.hpp
- src/nupic/algorithms/TemporalMemory.cpp
- src/nupic/algorithms/TemporalMemory.hpp
- src/test/unit/algorithms/TemporalMemoryTest.cpp
> Fix TM serialization bug, fix test so that it will catch it

- src/CMakeLists.txt
- src/nupic/algorithms/Svm.cpp
- src/nupic/algorithms/Svm.hpp
- src/nupic/proto/SvmProto.capnp
- src/test/unit/algorithms/SvmTest.cpp
@scottpurdy Please review.
Relevant commit is cf03aa5
> NUP-2339: Add Cap'n Proto serialization to SVM

- src/nupic/algorithms/SpatialPooler.cpp
than using both min() and max() separately
Fixes #1325
> SP: optimize using minmax_element 25% faster

- src/CMakeLists.txt
- src/nupic/algorithms/Cell.cpp
- src/nupic/algorithms/Cell.hpp
- src/nupic/algorithms/Cells4.cpp
- src/nupic/algorithms/Cells4.hpp
- src/nupic/algorithms/Segment.hpp
- src/nupic/algorithms/SegmentUpdate.hpp
- src/nupic/proto/Cell.capnp
- src/nupic/proto/Cells4.capnp
- src/nupic/proto/Segment.capnp
- src/nupic/proto/SegmentUpdate.capnp
- src/test/unit/algorithms/Cells4Test.cpp
fixes NUP-2341, NUP-2343, and NUP-2340
> Add serialization for Cells4, Cell, Segment, SegmentUpdate, CState, etc

- src/nupic/bindings/algorithms.i
- src/nupic/bindings/sparse_matrix.i
> NUP-2341: Add missing 'getSchema'

- src/nupic/bindings/algorithms.i
@scottpurdy Please review. This PR is required for the examples to work with the new serialization. See https://github.com/numenta/nupic/pull/3728
> NUP-2341: Expose capnp serialization to SVM swig interface

- ci/bamboo/build-linux-debug.sh
- ci/bamboo/build-linux-release.sh
- ci/bamboo/setup-dependencies-linux.sh
- ci/build-and-test-nupic-bindings.sh
This is required to update the Bamboo job to numenta-dev-default:0.5.0
> Fix issues in nupic.core build exposed with base image update

- README.md
- src/CMakeLists.txt
> Add option to force the installation of nupic include files

- src/CMakeLists.txt
> Install apr1 headers and swig interfaces

- bindings/py/tests/algorithms/cells4_test.py
- bindings/py/tests/nupic_random_test.py
- src/nupic/algorithms/Cell.cpp
- src/nupic/algorithms/Cell.hpp
- src/nupic/algorithms/Cells4.cpp
- src/nupic/algorithms/Cells4.hpp
- src/nupic/algorithms/InSynapse.hpp
- src/nupic/algorithms/Segment.cpp
- src/nupic/algorithms/Segment.hpp
- src/nupic/algorithms/SegmentUpdate.cpp
- src/nupic/algorithms/SegmentUpdate.hpp
- src/nupic/engine/Link.cpp
- src/nupic/engine/Link.hpp
- src/nupic/engine/Network.cpp
- src/nupic/engine/Network.hpp
- src/nupic/engine/Region.cpp
- src/nupic/engine/Region.hpp
- src/nupic/utils/Random.cpp
- src/nupic/utils/Random.hpp
- src/test/unit/algorithms/Cells4Test.cpp
- src/test/unit/algorithms/SegmentTest.cpp
- src/test/unit/engine/NetworkTest.cpp
- src/test/unit/utils/RandomTest.cpp
> NUP-2506: Add operator '==' to classes used in tests

- src/nupic/bindings/algorithms.i
- src/nupic/bindings/engine_internal.i
- src/nupic/bindings/math.i
- src/nupic/bindings/sparse_matrix.i
- src/nupic/engine/Region.cpp
- src/nupic/engine/Spec.cpp
- src/nupic/engine/Spec.hpp
- src/nupic/ntypes/Collection.cpp
- src/nupic/ntypes/Collection.hpp
- src/nupic/py_support/PyCapnp.hpp
- src/nupic/regions/PyRegion.cpp
- src/nupic/types/Serializable.hpp
- src/test/unit/ntypes/CollectionTest.cpp
This PR  fixes numenta/nupic#3808
@rhyolight Please review
> NUP-2514: Fix traversal limit

- circle.yml
- src/nupic/algorithms/SDRClassifier.cpp
- src/nupic/algorithms/SDRClassifier.hpp
- src/test/unit/algorithms/SDRClassifierTest.cpp
@rhyolight This PR adds a test to #1405
Please review
> NUP-2504: Add unit test to softmax overflow

- src/nupic/algorithms/SDRClassifier.cpp
- src/nupic/algorithms/SDRClassifier.hpp
https://github.com/numenta/nupic/pull/3819
same change
> Fix softmax overflow

- Dockerfile
- bindings/py/requirements.txt
- bindings/py/setup.py
- ci/travis/before_install-osx.sh
> NUP-2519: Upgrade pycapnp to 0.6.3

- bindings/py/tests/sparse_link_test.py
- setup.cfg
- src/nupic/engine/Input.cpp
- src/nupic/engine/Link.cpp
- src/nupic/engine/Link.hpp
- src/nupic/ntypes/ArrayBase.cpp
- src/nupic/ntypes/ArrayBase.hpp
- src/nupic/regions/PyRegion.cpp
> NUP-2507: Fix sparse links with propagation delay

- src/nupic/os/Directory.cpp
> Fix clang build, don't throw in a destructor
