numenta/nupic.core

src/CMakeLists.txt

Reverts numenta/nupic.core#295
that would disable all optimization (was only fallback) ..is not needed now. Tested in nupic #1695 SHA

Revert "disable temp. optimization flags"

---

src/nupic/os/Timer.cpp

I tested this by enabling timing in Cells4 and running `examples/opf/clients/hotgym/simple/hotgym.py` and it gives the correct units.
fixes #327.

Fixes #327 by enabling proper high resolution timing on OS X.

---

src/nupic/engine/Network.cpp
src/nupic/engine/Network.hpp
src/nupic/engine/Region.cpp
src/nupic/engine/Region.hpp
src/nupic/engine/RegionImplFactory.cpp
src/nupic/engine/RegionImplFactory.hpp

These modifications allow a user to create custom regions in Python. They just need to add the module to the network and then they can create their custom region.  There are changes for nupic as well.
Fixes https://github.com/numenta/nupic/issues/2057
@scottpurdy - please review

Allow registering custom Python regions

---

src/nupic/proto/TemporalMemoryProto.capnp

@scottpurdy 
I changed a parameter name in the temporal memory proto to be more descriptive. Please review and merge.

Change paramter name in temporal memory proto

---

src/nupic/engine/RegionImpl.cpp
src/nupic/engine/RegionImpl.hpp
src/nupic/engine/RegionImplFactory.cpp
src/nupic/engine/RegionImplFactory.hpp
src/nupic/engine/RegisteredRegionImpl.hpp
src/nupic/engine/TestNode.hpp
src/nupic/regions/VectorFileEffector.hpp
src/nupic/regions/VectorFileSensor.hpp

This adds serialization logic to the RegionImpl base class so that the Region class can serialize the various RegionImpl subclasses. It also provides read from / write to stream functions for each RegionImpl subclass.
fixes #477

Capnp RegionImpl serialization

---

src/nupic/engine/RegionImplFactory.cpp

Fixes: https://github.com/numenta/nupic.core/issues/480

Fixes 480: Rename cpp_region to py_region

---

src/examples/regions/HelloRegions.cpp
src/nupic/engine/Network.cpp
src/nupic/engine/Network.hpp
src/nupic/engine/Region.cpp

This implements the serialization for the Network class. This should enable entire networks to be serialized at once, although PyRegion serialization isn't implemented yet. This is difficult to create an integration test for since there are limited C++ regions available but this PR includes an example that should help validate that the basic paths work.
fixes #449 
@oxtopus  - please review

Implements capnp serialization for Network class

---

src/CMakeLists.txt
src/nupic/engine/Network.cpp
src/nupic/engine/Network.hpp
src/nupic/engine/Region.cpp
src/nupic/engine/Region.hpp
src/nupic/engine/RegionImplFactory.cpp
src/nupic/engine/RegionImplFactory.hpp
src/test/integration/PyRegionTest.cpp

Fixes #494
- Adds functionality to nupic.core to unregister regions. Needed in the case of name conflicts or overriding regions.
- Error is now thrown on registering an existing pyregion.
- Warning is now thrown on registering an existing cppregion.
- Updated integration tests for this functionality. 
- Also added the `tests_py_region` make target (builds/runs `src/test/integration/PyRegionTest.cpp`) and added to ```tests_all```

Add ability to unregister regions. Throws an error if registering existing region name

---

src/nupic/algorithms/Connections.cpp

Fixes https://github.com/numenta/nupic.core/issues/497.

Make Connections.mostActiveSegmentForCell ignore destroyed synapses

---

src/nupic/algorithms/Connections.cpp

Fixes https://github.com/numenta/nupic.core/issues/501.

Connections.mostActiveSegmentForCells should ignore synapses with 0 permanence

---

.travis.yml
appveyor.yml
bindings/py/setup.py
ci/travis/after_success-release-linux.sh
ci/travis/after_success-release-osx.sh
ci/travis/before_deploy.sh
setup.py

After we merged the SWIG files into nupic.core there was a problem with deployment:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/74106807/log.txt
I couldn't get it to find the pip-egg-info directory and have valid paths by just using the setup.py in bindings/py since I needed files that were in ../../external and I needed the relative path to the py_support files for the SWIG extensions. When I added a second setup.py to the root directory, symlinked pip-egg-info into bindings/py/pip-egg-info and executed the one in bindings/py from there, it worked.
This corrects the paths of setup.py so swig should be able to deploy on travis.
SO discussion: http://stackoverflow.com/questions/5317672/pip-not-finding-setup-file
@scottpurdy 
Fixes #528

correct paths for deployment of swig bindings

---

.travis.yml
ci/travis/after_success-release-osx.sh
ci/travis/before_deploy.sh

Added export ARCHFLAGS to before_deploy script if the platform is osx.
@scottpurdy

added export ARCHFLAGS for OS X deployment

---

.travis.yml
bindings/py/setup.py

Instead of deploying the zip of C++ files, this deploys the bindings wheel.
@scottpurdy

Upload bindings wheel to s3 for deployment

---

.travis.yml

Version.hpp and py_region_test are needed for nupic setup.py.  This adds them to the zip.
Fixes #538
@scottpurdy

include Version.hpp and py_region_test in bindings tar.gz

---

.travis.yml

When the user provides a local version of nupic.core the paths should match the released version.  This fixes the paths in the release version to match the local version.
@scottpurdy 
Fixes #540

correct paths for additional files in nupic.bindings release

---

ci/travis/after_success-release-linux.sh
ci/travis/after_success-release-osx.sh

Updated the setup.py call so we don't use bdist_egg
@rhyolight

after release without bdist_egg command

---

.travis.yml
appveyor.yml
bindings/py/setup.py
ci/travis/after_success-release-linux.sh
ci/travis/after_success-release-osx.sh
ci/travis/before_deploy.sh

Now the user must use the flag --nupic-core-dir when calling setup.py.  This should allow us to eliminate the setup.py that is at the top level as well since that was just there to run "pip wheel ." and we no longer run that.
Fixes #551
@oxtopus @scottpurdy

Remove dependency on NUPIC_CORE_RELEASE environment variable

---

src/CMakeLists.txt

Explicitly set capnpc import dir for generating the C++ code.

---

bindings/py/requirements.txt

Removes pycapnp from nupic.bindings requirements.

---

.travis.yml
bindings/py/setup.py

These were needed when capnp libs/headers weren't included in install but as of #598 this is resolved.
fixes #596 (again)
@oxtopus please review - forgot this clean up step

Remove CPPFLAGS and LDFLAGS that aren't needed.

---

.travis.yml
README.md

fixes #602 
@rhyolight @oxtopus - What do you guys think about this for running Python tests? We decided a while back to move tests into the python packages so they are on the PYTHONPATH (in an internal email chain titled "A few Python convention changes"). One advantage is that we can run them like this to ensure we are running the version of the tests that corresponds to the version that is installed.
Let me know what you think about the `--pyargs` option for running Python tests via Python import path instead of disk path.

Use py.test --pyargs option for collecting nupic.bindings tests.

---

bindings/py/setup.py

Fixes #615 
Currently experiencing non-deterministic results due to different versions of nupic.core that share a common 0.1.5 semantic version.

Bump version to 0.2 to reflect change in behavior of nupic.bindings.math.Random

---

bindings/py/setup.py
src/nupic/algorithms/Segment.cpp
src/nupic/math/SparseBinaryMatrix.hpp

Fixes #616
re: TODO in `Segment::freeNSynapses()` to apply stable sort to consistently break ties between multiple synapses with the same lowest permanence.  This comes with a possible speed hit, since std::stable_sort() is slower than std::sort(), but gives me consistent behavior where I was otherwise getting divergent results.
cc @scottpurdy

Use stable sort in Segment::freeNSynapses()

---

src/nupic/algorithms/Cells4.cpp

643: Request an exception on logical/physical I/O error and explicitly close the file stream

---

CMakeLists.txt
external/CMakeLists.txt
src/CMakeLists.txt
src/nupic/regions/PyRegion.hpp

fixes #656
@jcasner is using brewed Python and having the Python include path show up before our hard-coded vendored dependencies caused problems since Boost was installed on his system with same include prefix as Python. This PR is primarily to make sure that our hard coded externals are before any introspected paths.
I also switched our source files to not be specified as `SYSTEM` includes which exposed so issues in PyRegion.hpp that I fixed.

Fix include order for cmake

---

external/CapnProto.cmake
src/CMakeLists.txt

There was a bug in the cmake that caused everything to rebuild no matter what on both `make` and `make install`. This fixes that issue while still ensuring that the .capnp schema files show up in XCode IDE.
fixes #655 
@rcrowder - fyi

Prevents rebuilding libraries regardless of changes

---

src/test/unit/math/SparseBinaryMatrixTest.cpp
src/test/unit/math/SparseMatrixTest.cpp

Fixes #719 
Note that no tests had to be translated to gtest for this sub-issue. All tests were already using gtest or were commented out as addressed in #376. I did remove unnecessary namespaces from the gtest test cases as has been the convention.
@scottpurdy

Remove Tester class for test in tests/unit/math

---

src/CMakeLists.txt

Fixes #809
One of the great things about CMake is being able to use `ninja` (https://ninja-build.org/) by specifying `cmake -GNinja`. I gave it a shot but ran into some errors (nothing major; the things would probably be worth fixing anyway). More details in the commit messages.
I'm building locally with this configure line (on Ubuntu 15.04):
```
cmake -GNinja $NUPIC_CORE -DCMAKE_INSTALL_PREFIX=../ninja-release -DPY_EXTENSIONS_DIR=$NUPIC_CORE/bindings/py/nupic/bindings -DFIND_CAPNP=ON -DFIND_SWIG=ON
```
Some potentially relevant reviewers (and the relevant commits I found them by)
@oxtopus ddc622bf99c886692f2b19892a56ecc70e8fa5de
@rcrowder 6258ba8016e71e13103b2b495c99f585cba733f4

Fixes for building with `cmake -GNinja`

---

src/CMakeLists.txt

The only build target that is an input to this build step is
${LIB_STATIC_NUPICCORE}, so that is all it should depend on. All the
other inputs are determined at configure time and reside in
`nupic.core/external`.
I noticed this when touching
`nupic.core/src/test/integration/ConnectionsPerformanceTest.cpp`
which is needed for the ${EXECUTABLE_CONNECTIONSPERFORMANCETEST} target.
This would cause ${LIB_STATIC_NUPICCORE_COMBINED} to be rebuilt as well,
which would also trigger rebuilding the SWIG bindings (which takes a
while).
Fixes #810

Remove unnecessary dependencies for ${LIB_STATIC_NUPICCORE_COMBINED}

---

src/nupic/algorithms/TemporalMemory.cpp

Fixes https://github.com/numenta/nupic.core/issues/848.

Temporal Memory: recordIteration should be false in second call to computeActivity

---

src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/TemporalMemory.cpp
src/nupic/bindings/algorithms.i

Fix: TM compatibility tests fail when predictedSegmentDecrement is nonzero

---

src/CMakeLists.txt
src/nupic/encoders/Base.hpp
src/nupic/encoders/Scalar.cpp
src/nupic/encoders/Scalar.hpp
src/test/unit/encoders/ScalarTest.cpp

Fixes #533 
Also addresses part of #366 
The abstract encoder base is pretty bare. Eventually a few more methods might get added to it. The noteworthy part is the signature of the `encodeIntoArray` method. We pass in arbitrary types to the encoder via an `Array` or `ArrayRef`.
For the ScalarEncoder, I didn't just translate the Python version to C++. I looked at the Python version's behavior and tried to describe it in simple terms. I found that it actually took two simple explanations, one for `periodic=true` and one for `periodic=false`, so I split it into two classes: `ScalarEncoder` and `PeriodicScalarEncoder`. I explain how they work in `Scalar.hpp`.
I ported the Python tests that check the `encode` functionality, then I absorbed them into my own set.

C++ Encoder base, ScalarEncoder

---

src/CMakeLists.txt
src/nupic/encoders/EncoderBase.hpp
src/nupic/encoders/ScalarEncoder.cpp
src/nupic/encoders/ScalarEncoder.hpp
src/test/unit/encoders/ScalarEncoderTest.cpp

Fixes #870 
This change adjusts to the new upcoming design, where encoders are enclosed in type-aware Regions and hence don't need to use an ArrayBase.
It also begins to introduce the concept of the "bucket" into the interface. encodeIntoArray returns a bucket, and the comment explains what it's for.

New encoder method signature, class hierarchy

---

src/nupic/engine/YAMLUtils.cpp
src/nupic/ntypes/Scalar.cpp
src/nupic/ntypes/Scalar.hpp
src/nupic/ntypes/Value.cpp
src/nupic/types/BasicType.cpp
src/nupic/types/Types.h
src/test/unit/engine/YAMLUtilsTest.cpp
src/test/unit/ntypes/ArrayTest.cpp
src/test/unit/ntypes/ScalarTest.cpp
src/test/unit/types/BasicTypeTest.cpp

Fixes #488 
In an upcoming change, encoder params are now sent to regions as YAML, and we want to be able to use bools in encoder params since they're very user-facing.
In this change I avoided cargo-culting. As mentioned in the comment above the NTA_BasicType_Bool declaration,  I didn't create a typedef's `Bool` or `NTA_Bool`. I don't see a reason for those to exist in this case, but I might be oblivious to something. (Otherwise I don't want to plague the codebase with "Should this be a `Bool` or a `bool`?" ambiguity.)

Add a NTA_BasicType_Bool so that we can parse bools in YAML

---

bindings/py/nupic/bindings/regions/TestNode.py
src/nupic/bindings/engine_internal.i
src/nupic/engine/Region.hpp
src/nupic/engine/RegionImpl.cpp
src/nupic/engine/RegionImpl.hpp
src/nupic/engine/RegionParameters.cpp
src/nupic/engine/TestNode.cpp
src/nupic/engine/TestNode.hpp
src/nupic/ntypes/Buffer.cpp
src/nupic/ntypes/Buffer.hpp
src/nupic/ntypes/ObjectModel.hpp
src/nupic/ntypes/Value.cpp
src/nupic/proto/TestNodeProto.capnp
src/nupic/py_support/PyArray.cpp
src/nupic/py_support/PyArray.hpp
src/nupic/py_support/PyHelpers.cpp
src/nupic/py_support/PyHelpers.hpp
src/nupic/regions/PyRegion.cpp
src/nupic/regions/PyRegion.hpp
src/nupic/types/BasicType.cpp
src/test/integration/PyRegionTest.cpp
src/test/unit/ntypes/ArrayTest.cpp
src/test/unit/types/BasicTypeTest.cpp

Fixes #883 
Also switch to using "Bool" when referring to it as a string. Python code uses this string to assemble a method name, e.g. "setParameter" + "Bool".

Finish adding support for the Bool type

---

src/nupic/encoders/ScalarSensor.cpp

CC @mrcslws @scottpurdy 
Indeed, this did the trick on my Win32 build on AWS instance.
The error on the win32 build looked like this:
```
C:\projects\nupic-core\src\nupic\encoders\ScalarSensor.cpp: In member function 'virtual void nupic::ScalarSensor::getParameterFromBuffer(const string&, nupic::Int64, nupic::IWriteBuffer&)':
C:\projects\nupic-core\src\nupic\encoders\ScalarSensor.cpp:235:45: error: call of overloaded 'write(int)' is ambiguous
value.write(encoder_->getOutputWidth());
^
C:\projects\nupic-core\src\nupic\encoders\ScalarSensor.cpp:235:45: note: candidates are:
In file included from C:/projects/nupic-core/src/nupic/engine/RegionImpl.hpp:43:0,
from C:/projects/nupic-core/src/nupic/encoders/ScalarSensor.hpp:39,
from C:\projects\nupic-core\src\nupic\encoders\ScalarSensor.cpp:34: …
```

Cast arg to UInt32 to avoid call resolution ambiguity on the value.write() method on Win32 platform.

---

src/nupic/algorithms/TemporalMemory.cpp

Fixes #893 
Results:
Using temporalImp "tm_cpp", and running:
`time python $NUPIC/examples/opf/clients/hotgym/simple/hotgym.py`
Before this change:
~~~
real	0m32.101s
user	0m31.874s
sys	0m0.202s
~~~
After this change:
~~~
real	0m13.201s
user	0m12.971s
sys	0m0.205s
~~~
Profiling it, after this change:
- 24.0% of runtime is spent in TemporalMemory::compute
- 11.7% of runtime is spent in SpatialPooler::compute
- 28.7% of runtime is spent in FastCLAClassifier::fastCompute

Perf: When using sets, use std::set::find, not std::find

---

appveyor.yml
src/test/unit/algorithms/SpatialPoolerTest.cpp

- Fix error in windows32 build caused by floating point differences.
- Enable errors in windows32 builds.
fixes #898

Fix test that fails on windows32 and enable errors for windows32 build

---

src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/Connections.hpp
src/test/unit/algorithms/ConnectionsTest.cpp

Fixes #899 
Add tests for a set of potential bugs.
After my changes to the tests, in the current implementation these tests fail:
[  FAILED  ] ConnectionsTest.testSynapseReuse
[  FAILED  ] ConnectionsTest.DestroySegmentsThenReachLimit
[  FAILED  ] ConnectionsTest.DestroySynapsesThenReachLimit
[  FAILED  ] ConnectionsTest.ReachSynapseLimitMultipleTimes
Fix the bugs. These tests pass now.
I also did performance tweaks in functions that I touched. It's now 11% faster.
Here's the output for
~~~
python $NUPIC/scripts/temporal_memory_performance_benchmark.py
~~~
Reference:
TP10X2: 1.647582s
Before:
TM (C++): 2.782499s
After:
TM (C++): 2.50993s

Fix issues with destroySegment / destroySynapse

---

src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/Connections.hpp
src/test/integration/ConnectionsPerformanceTest.cpp
src/test/integration/ConnectionsPerformanceTest.hpp
src/test/unit/algorithms/ConnectionsTest.cpp

Fixes #906 
Here's the output for:
~~~
python $NUPIC/scripts/temporal_memory_performance_benchmark.py
~~~
Reference:
TP10X2: 1.65675s
Before:
TM (C++): 2.607865s
After:
TM (C++): 1.670907s

Stop storing segment overlap counts in a map. Now 56% faster.

---

src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/Connections.hpp
src/nupic/algorithms/TemporalMemory.cpp
src/test/integration/ConnectionsPerformanceTest.cpp
src/test/unit/algorithms/ConnectionsTest.cpp

Fixes #910 
Here's the output for:
~~~
python $NUPIC/scripts/temporal_memory_performance_benchmark.py
~~~
Reference:
TP10X2: 1.625308s
Before:
TM (C++): 1.613453s
After:
TM (C++): 1.550195s

Stop computing overlaps twice per timestep. 4% faster.

---

appveyor.yml
bindings/py/nupic/bindings/check.py
bindings/py/tests/check_test.py

This runs the Python tests in AppVeyor and also updates the bindings check test to include the exception message in the output.
@vitaly-krugl - please review
I'd like to merge this even though it is red because the current green build produces a broken win64 library.
fixes #913

Add Python tests to AV build.

---

bindings/py/nupic/bindings/regions/PyRegion.py
src/nupic/regions/PyRegion.cpp

Fixes #930 
Originally I prototyped https://github.com/numenta/nupic.core/pull/918 but I think it's better to require Python code to use the pre-allocated arrays, and to fail loudly when it doesn't.
Now if you reassign an output, you'll get:
~~~
TypeError: 'DictReadOnlyWrapper' object does not support item assignment
~~~

Fail loudly when Python regions reassign an output

---

src/CMakeLists.txt
src/nupic/engine/RegionImpl.cpp

Fixes #928
I verified that the expression inside NTA_ASSERT is no longer evaluated on release builds.

Disable asserts in release builds

---

ci/bamboo/build-linux-debug.sh
ci/bamboo/build-linux-release.sh
ci/bamboo/build-linux.sh
ci/bamboo/setup-dependencies.sh

@mrcslws fyi
fixes #941
This splits the Bamboo build script for linux into two:
- One builds in debug mode with coverage enabled and does not produce eggs or wheels. The coverage info will be extracted from this job.
- One builds in release mode with coverage disabled and produces binary and source distributions. The release artifacts will be extracted from this job.

Build debug and release mode in Bamboo

---

README.md
src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/Connections.hpp
src/nupic/algorithms/TemporalMemory.cpp
src/nupic/algorithms/TemporalMemory.hpp
src/nupic/proto/ConnectionsProto.capnp
src/nupic/proto/TemporalMemoryProto.capnp
src/test/integration/ConnectionsPerformanceTest.cpp
src/test/integration/ConnectionsPerformanceTest.hpp
src/test/unit/algorithms/ConnectionsTest.cpp
src/test/unit/algorithms/TemporalMemoryTest.cpp

To describe this change, I'll start by describing the current code.
Currently the TemporalMemory algorithm is implemented as a series of phases:
- Activate the correctly predictive cells.
- Burst unpredicted columns.
- Perform learning by adapting segments.
- Compute predictive cells due to lateral input on distal dendrites
Through all of this, it's maintaining a central set of data: activeColumns, activeCells, winnerCells, predictedActiveColumns, predictedInactiveCells, predictiveCells, matchingCells, learningSegments, activeSegments, matchingSegments.
Phases 1 and 2 each append to the data. Phases 1, 2, and 3 do lookups in the data.
Phase 1 walks the predicted cells, checking which are active, doing one set lookup per predicted cell. Similarly, it walks the matching cells, doing one set …

TemporalMemory: replace phases with "columnSegmentWalk". Much faster.

---

src/CMakeLists.txt

fixes #342
This provides the CMake option `NUPIC_IWYU`. If enabled, it attempts to find the iwyu executable and runs it on NuPIC sources, printing recommendations to stderr during `make` execution.

Adds include-what-you-use option in CMake configuration.

---

src/test/unit/os/TimerTest.cpp

I was just curious if the `Timer` does not accumulate any delay drift over many consecutive restarts. 
Seems that it does not :+1: 
A tiny unit-test, I thought I'd share it when I wrote it. 
Fixes #965

Timer: test drift

---

src/nupic/engine/Spec.cpp
src/nupic/engine/Spec.hpp
src/nupic/regions/PyRegion.cpp

fixes: #979 
makes regionLevel and requireSplitterMap optional parameters and gives them default values in PyRegion.cpp.
Please review:
@subutai @scottpurdy

deprecate-spec-vars set defaults for deprecated variables

---

ci/bamboo/build-osx.sh

This fixes the path so that the pip and py.test commands are in PATH.

DEVOPS-84 Fixup os x build

---

src/CMakeLists.txt
src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/Connections.hpp
src/nupic/algorithms/TemporalMemory.cpp
src/nupic/algorithms/TemporalMemory.hpp
src/nupic/bindings/algorithms.i
src/nupic/bindings/experimental.i
src/nupic/experimental/ExtendedTemporalMemory.cpp
src/nupic/experimental/ExtendedTemporalMemory.hpp
src/nupic/proto/ExtendedTemporalMemoryProto.capnp
src/test/integration/ConnectionsPerformanceTest.cpp
src/test/integration/ConnectionsPerformanceTest.hpp
src/test/unit/algorithms/ConnectionsTest.cpp
src/test/unit/algorithms/TemporalMemoryTest.cpp

This change adds an `ExtendedTemporalMemory` class that supports external connections. It puts it in a new `nupic::experimental` namespace. In the Python bindings this is `nupic.bindings.experimental`.
This ETM doesn't yet support apical dendrites or "learn-on-one-cell".
**I recommend looking at the individual commits, not the PR as a whole.**
I aimed for clean code that avoids unnecessary computation. I avoided making copies of lists of cells -- I don't combine the "internal active cells" and "external active cells" into a separate "all active cells" list. This decision led me to rework the Connections `computeActivity` so that we could compute segment excitations without having to flatten all the active cells into a single list.
The `ExtendedTemporalMemory` looks a lot like the …

C++ ExtendedTemporalMemory: Part 1

---

README.md
src/nupic/bindings/algorithms.i
src/nupic/bindings/experimental.i

The default SWIG implementation of columnForCell is now good enough. When I removed the custom implementation, I forgot to remove the %ignore directive.
Fixes #1011

Re-add columnForCell to the SWIG bindings

---

src/nupic/algorithms/FastClaClassifier.cpp
src/nupic/algorithms/FastClaClassifier.hpp
src/nupic/algorithms/SDRClassifier.cpp
src/nupic/algorithms/SDRClassifier.hpp
src/nupic/bindings/algorithms.i

Fixes #1019 (and, a bit too late, numenta/nupic#3231) by updating the bindings to include the new C++ SDRClassifier, which will be ready to use after this PR is merged.
There is also a slight update in a global variable's name in both CLA and SDR classifiers, as they were conflicting in the generated bindings.
@rhyolight @scottpurdy

Updates bindings to handle SDR classifier

---

src/nupic/bindings/algorithms.i

Fixes #1023.
The version is now compared to the class variable's values rather than 0.

Fixes version bug in SDR classifier deserialization

---

CMakeLists.txt
CommonCompilerConfig.cmake
ci/bamboo/bootstrap-manylinux-prototype.sh
ci/bamboo/build-manylinux-prototype.sh
external/Zlib.cmake
external/common/share/zlib/README.md
external/common/share/zlib/zlib.patch
src/CMakeLists.txt
src/nupic/math/ArrayAlgo.hpp

CC @scottpurdy 
Fixes #1025
NOTES: 
1. The manylinux wheel generated by this PR passes all [nupic tests](https://github.com/numenta/nupic/tree/master/tests) on Ubuntu 14.04, but hangs some of the tests that use capnp serialization in the nupic.bindings extension on Ubuntu 16.04 as described on https://mail.python.org/pipermail/wheel-builders/2016-July/000199.html.
1.1 The hang will be addressed by a separate PR per issue #1013
2. Contains several other useful fixes for issues that I encountered along the way that blocked progress of this PR (see commit notes for details).
This proof-of-concept enables a build of a nupic.bindings manylinux wheel by executing 
```[sudo] ci/bamboo/bootstrap-manylinux-prototype.sh```
from the root of the nupic.core repo. After the command completes, the …

DEVOPS-116 proof-of-concept build of nupic.bindings manylinux wheel 

---

src/nupic/algorithms/SDRClassifier.cpp

Fixes #1026.
This was a bug which needed a specific situation to reproduce (using a de-serialized classifier for multi-step prediction).
Sorry @scottpurdy, hopefully we should be done with this...

Fixes indexing bug in SDRClassifier serialization

---

src/CMakeLists.txt
src/nupic/bindings/experimental.i
src/nupic/experimental/ExtendedTemporalMemory.cpp
src/nupic/experimental/ExtendedTemporalMemory.hpp
src/nupic/proto/ExtendedTemporalMemoryProto.capnp
src/nupic/utils/GroupBy.hpp
src/test/unit/experimental/ExtendedTemporalMemoryTest.cpp
src/test/unit/utils/GroupByTest.cpp

The SWIG bindings give it an identical interface to the current Python ExtendedTemporalMemory.
Introduces the distinction "basal" vs "apical".
Additional changes:
- Rework getLeastUsedCell to be non-allocating.
- Put ExcitedColumns in a namespace so that it doesn't collide with the one in TemporalMemory.
- Fix a serialization bug that is also in TemporalMemory. save and load weren't writing and reading in the same order.
- Fix a bad bug with external cells: I wasn't shifting their index during activateDendrites
- Copy-paste a set of ExtendedTemporalMemory unit tests
This passes the [extensive_etm_test](https://github.com/numenta/nupic.research/blob/5230a39e3adf9f62aa16d146ad8415d0bfb9f7da/tests/extended_temporal_memory/extensive_etm_test.py), with the following caveats:
- It doesn't …

Add apical dendrites to ExtendedTemporalMemory

---

CommonCompilerConfig.cmake
external/Apr1Lib.cmake
external/AprUtil1Lib.cmake

Fixes #1031
Tested build on Ubuntu 16.04 running in VirtualBox.

Fixes AR and RANLIB settings for Release builds of configure-based externals with g++ >=4.9

---

src/test/unit/algorithms/SDRClassifierTest.cpp

Fixes #1026 by adding a unit test for testing that there is no interference between multi-step prediction and serialization (which used to be the case before #1027 was merged).

Improves SDRClassifier's unit test for serialization

---

CommonCompilerConfig.cmake
src/CMakeLists.txt

Fixes #1040 
The manylinux wheel build of this PR passes all nupic.core and nupic tests (unit, integration, swarming) on Ubuntu 16.04 !!!
Use shared libgcc and static libstdc++ on linux python extension builds.
Apply an export map to OS X, Linux, and MINGW builds of nupic.bindings shared objects.
Refactor extension build steps into a function shared by algorithms, math, engine_internal, etc. in preparation for adding export maps.

DEVOPS-141 Prevent symbol preemption of c++ references to static stdc++

---

src/CMakeLists.txt

Fixes #1056
NUP-2300 use add_dependencies to set swig module dependencies instead of setting SWIG_MODULE_${MODULE_NAME}_EXTRA_DEPS, which doesn't work.
It looks like cmake's `set` function doesn't allow the destination variable name to be composed from other variables.

NUP-2300 Fix parallel build failure

---

src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/Connections.hpp
src/nupic/algorithms/TemporalMemory.cpp
src/nupic/algorithms/TemporalMemory.hpp
src/nupic/experimental/ExtendedTemporalMemory.cpp
src/nupic/utils/GroupBy.hpp
src/test/unit/algorithms/TemporalMemoryTest.cpp
src/test/unit/experimental/ExtendedTemporalMemoryTest.cpp

Fixes #1058
This PR does a few things:
- Makes the TM and ETM learn on predicted segments. To keep this clean, I reworked some code, especially in the ETM.
- Makes the TM more similar to the ETM. Specifically, the implementations of `activatePredictedColumn`, and having the `activateCells` and `activateDendrites` phases.
- Does some last-minute ETM cleanup before we code the Python version. Specifically, stop making `learnOnCell` search the segments lists for the cell's segments -- calculate these before calling learnOnCell.

Grow synapses in predicted columns, not just bursting columns

---

README.md

@rhyolight, this is unrelated to #1069; just some important technical debt that I remembered to fulfill. Please review this tiny change.

Added information about usage of the NUPIC_BUILD_PYEXT_MODULES cmake property

---

src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/Connections.hpp
src/nupic/algorithms/TemporalMemory.cpp
src/nupic/algorithms/TemporalMemory.hpp
src/nupic/experimental/ExtendedTemporalMemory.cpp
src/nupic/experimental/ExtendedTemporalMemory.hpp
src/test/integration/ConnectionsPerformanceTest.cpp
src/test/integration/ConnectionsPerformanceTest.hpp
src/test/unit/algorithms/ConnectionsTest.cpp
src/test/unit/algorithms/TemporalMemoryTest.cpp
src/test/unit/experimental/ExtendedTemporalMemoryTest.cpp

Fixes #1062
Here's the matching Python change, with additional changes: https://github.com/numenta/nupic/pull/3307
This change stops passing around Segment + Overlap pairs. Instead, `activeSegments` and `matchingSegments` are simply lists of segments, and we keep the internals of `computeActivity` available so that we can look up the "overlap" of any segment. We don't call it the "overlap" any more, we refer specifically to the `numActivePotentialSynapsesForSegment` and `numActiveConnectedSynapsesForSegment`.
This simplifies the code, especially `activatePredictedColumn`, and it's just cleaner in principle. Also it's a little faster.
Before:
~~~
> python scripts/temporal_memory_performance_benchmark.py -i tm_cpp -t hotgym
Test: hotgym
tm_cpp: 0.776342s
~~~
After:
~~~
> python …

TM: Abolish the SegmentOverlap

---

src/nupic/algorithms/SpatialPooler.cpp
src/nupic/algorithms/SpatialPooler.hpp
src/test/unit/algorithms/SpatialPoolerTest.cpp

Fixes #1053
This is the C++ counterpart to https://github.com/numenta/nupic/pull/3296
With these C++/Python changes combined, the `spatial_pooler_compatibility_test` passes.

SP: Properly handle column overlap of 0

---

src/nupic/algorithms/TemporalMemory.cpp
src/nupic/algorithms/TemporalMemory.hpp
src/nupic/bindings/algorithms.i
src/nupic/bindings/experimental.i
src/nupic/experimental/ExtendedTemporalMemory.cpp
src/nupic/experimental/ExtendedTemporalMemory.hpp
src/test/unit/algorithms/TemporalMemoryTest.cpp
src/test/unit/experimental/ExtendedTemporalMemoryTest.cpp

Fixes #1073
Building a `const vector<UInt>&` from a numpy array is expensive. At the very least, it requires copying the array, because there's (sadly) no way to construct a `const vector<UInt>&` from a `UInt[]`. On top of that, when you convert a numpy array to a vector, SWIG calls `PyLong_AsUnsignedLong` on every entry in the array. This is very slow. (Also, it shouldn't be necessary since the numpy `uint32` is already formatted correctly for C.)
Fundamentally, using vectors as inputs in a public API is a limiting move. It forces your callers to use vectors, or to pay the cost of copying their input into a vector. It's better to build APIs that use C arrays, because then anyone who stores their data in contiguous blocks of memory is free to call your API on their data.
With this change, …

Use C arrays as (Extended)TemporalMemory inputs

---

ci/bamboo/build-windows.ps1

Fixes #1075
Follow-on fix to the merged PR #1082

Add missing argument to `Set-PsDebug -Trace`

---

src/CMakeLists.txt
src/nupic/algorithms/SpatialPooler.cpp
src/nupic/algorithms/SpatialPooler.hpp
src/nupic/math/Topology.cpp
src/nupic/math/Topology.hpp
src/test/unit/algorithms/SpatialPoolerTest.cpp
src/test/unit/math/TopologyTest.cpp

Introduces a `Neighborhood` class which lets you iterate over all points in a neighborhood without ever creating a list of points.
This change also fixes a bug in the SP's `mapColumn_`. When I removed the `sort` call, the compatibility tests started failing, and this was the root cause.
Fixes #1079 
Fixes #1080
Fixes #128 (no more extraneous sorting)
This affects algorithm results for two reasons:
- We walk neighbors in a different order.
- `mapColumn_` is no longer broken.
- Though this bug wasn't showing up in the SP compatibility tests until I removed neighbor sorting.
**Before:**
~~~
> time python nupic.research/projects/sp_paper/train_sp_topology_simple.py
real	0m51.560s
~~~
**After:**
~~~
> time python nupic.research/projects/sp_paper/train_sp_topology_simple.py
real	0m7.755s
~~~
So …

Faster local inhibition: Stop creating lists of neighbors

---

ci/bamboo/build-windows.ps1
ci/build-and-test-nupic-bindings.sh

@vitaly-krugl please review - the connections performance test in particular is really long and just wasn't intended as a CI test. I'm not sure we even care that much to keep it from breaking but we could create a nightly build or something if we want to run it regularly.
CC @rhyolight @oxtopus

Reduce build times by removing some executables from build.

---

src/nupic/bindings/experimental.i
src/nupic/experimental/ExtendedTemporalMemory.cpp
src/nupic/experimental/ExtendedTemporalMemory.hpp
src/test/unit/experimental/ExtendedTemporalMemoryTest.cpp

This change adds 3 parameters to the ETM:
- "checkInputs" - Tell the ETM to perform a bunch of slow checks on the input. We'll usually have this turned on.
- "basalInputDimensions" - Used for input checking, for visualizations, and maybe for future use in the ETM. (Up until now we've had to design around not knowing this)
- "apicalInputDimensions" - Same as above
Second, this change stops assuming that the "active external cells" are also "winner cells". They are now passed in as "reinforce candidates" and "growth candidates". So now we'll be able to respond appropriately to external bursting columns, only growing synapses to the winner cells.
Third, this change embraces this terminology. It never describes external inputs as "prev active" or "prev winner". Instead it calls them …

ETM: Split external active cells from winner cells. Check inputs.

---

appveyor.yml

fixes #1128
Iterative artifacts have been stored on S3 with the software version in
the name of the file. This means any system that wants to fetch an
artifact for a SHA not only needs to know the SHA, but also the version
of the software, which is redundant and requires inspecting the source
tree to find. This removes the version from the filename so artifacts
are easier to find later.

Removes version as part of iterative artifact name

---

src/nupic/algorithms/SpatialPooler.cpp
src/nupic/algorithms/SpatialPooler.hpp

Fixes #1160
Rather than making a copy of the overlaps and using the same logic, this change moves away from doing the tie-break logic with math and an "arbitration" constant. Instead, it handles the tie-break case explicitly, checking if the neighboring column is selected in the event of a tie.
This change makes the code less error-prone because:
1. We're not corrupting the overlaps (which are exposed via `getBoostedOverlaps`)
2. We're not having to use a heuristic to choose an arbitration constant.

SP: Stop putting tie-break info in the overlaps

---

src/nupic/bindings/algorithms.i
src/nupic/bindings/sparse_matrix.i
src/nupic/regions/VectorFileSensor.cpp

Fixes #1161
This flag is still not fully supported. For example, the sparse_binary_matrix bindings tests will crash with this flag enabled. But this change is enough to fix the build and to get it working at runtime with the Python SpatialPooler.

Fix some build and runtime errors with NTA_DOUBLE_PRECISION

---

src/examples/prototest.cpp
src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/SpatialPooler.cpp
src/nupic/algorithms/TemporalMemory.cpp

Fixes #1165
I went ahead and also made the change in the Connections and the TemporalMemory.
I tried to write this in a way that is pretty robust. This approach lets us use any mix of float32 and float64, and the code will just keep working.

Stop changing floats during save/load serialization

---

src/nupic/algorithms/SpatialPooler.cpp
src/test/unit/algorithms/SpatialPoolerTest.cpp

Fixes #1175
Actually, it gives up on trying to get identical boost factors between implementations. This is proving too difficult.
Instead, we'll use a similar strategy to what we do with permanences: https://github.com/numenta/nupic/blob/380bf1be4a62c961a9af0ebfa3def63b6c6141eb/tests/unit/nupic/research/spatial_pooler_compatability_test.py#L205
We'll make sure the boost factors are "close enough", and then force them to be equal so that little variations don't cause different columns to become active.
I put a lot of thought into this. Our options are:
1. Write two implementations that get identical results.
2. Use shared C code to handle boost factors, duty cycles, etc.
3. Only expect totally identical results in very controlled environments (like the spatial pooler compatibility test)
I …

SP: Stop rounding the boost factors

---

bindings/py/tests/sparse_matrix_test.py
src/nupic/bindings/sparse_matrix.i
src/nupic/math/SparseMatrix.hpp

With this change, `SparseMatrix.hpp` now has:
- rightVecSumAtNZ
- rightVecSumAtNZSparse **(new)**
- rightVecSumAtNZGtThreshold
- rightVecSumAtNZGtThresholdSparse **(new)**
- rightVecSumAtNZGteThreshold **(new)**
- rightVecSumAtNZGteThresholdSparse **(new)**
In the bindings, I get rid of having variants like `rightVecSumAtNZ`, and instead add an `out` parameter to the methods. So it feels like numpy.
Fixes #1190

SparseMatrix: rightVecSumAtNZ cleanup

---

src/nupic/bindings/sparse_matrix.i
src/nupic/py_support/NumpyVector.hpp

The approach: use `numpy.asarray` to get a numpy array. This function only copies the array if necessary. So these methods will never silently fail. Then the C code will use the memory buffer of the numpy array.
Fixes #1186
(Well, it fixes it partly. I only changed this for the methods that I'm using in the TemporalMemory.)

SparseMatrix: Stop copying input vectors

---

.travis.yml
src/CombineUnixArchives.cmake

Fixes #1095.
NUP-2316 Fixed globbing statement that was picking up unexpected files after obj extraction (e.g., sort index file) and packaging then into the new archive.
NUP-2316 Add error-checks after archive extraction and construction commands.
I tested the fix on a OS X Sierra MacBookPro. I confirmed the failure before the fix and verified the fix afterwards.
NOTE1: also tried building on Travis using xcode8.2 OS X image (macos10.12-xcode8.2) at experimental commit bd8a79b7fe90c9e88580906a9f46d443fe265b23. nupic.core build succeeded; the build failed later on in the installation step. See https://s3.amazonaws.com/archive.travis-ci.org/jobs/191535267/log.txt. This was just an experiment. Switching the Travis build to xcode8* is outside the scope of this task.
NOTE2: at experimental …

NUP-2316 Installing XCode 8 makes nupic.core build fail

---

.travis.yml
ci/travis/before_install-osx.sh

Per documentation at https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
Fixes #1209
Regard this as temporary until Travis-CI configuration and relevant build scripts are updated for full xcode8 support.

Use xcode6.4 image in Travis-CI

---

circle.yml

This is a proof-of-concept for Circle CI OS X build.
fixes #1219 
Note the following Circle CI limitations discovered so far:
- The circle environment has some inferred stages that cannot be overridden. One of these is setting up virtualenv when it detects a Python project.
- There is a bug in the circle environment where virtualenv is missing but the inferred stage requires it. I found a solution online where you install it in the machine "pre" section.
- I have found no way to get a newer version of pip. I tried while inside the virtualenv but the pip being used is from the system installation. And the circle .bashrc/.bash_profile modifies the PATH (AFTER applying the `PATH` changes made in the machine "environment" section) so that `/usr/local/bin` occurs before anything that I set.
- …

Circle CI initial yaml file

---

circle.yml

The hack I needed to make virtualenv available doesn't always seem to be necessary as virtualenv is already present in the target location when Circle runs jobs from the "numenta" fork of nupic.core. This change makes the symlinking happen only when virtualenv isn't yet present.
@oxtopus @rhyolight someone review when you have a chance

Add conditional to virtualenv symlink in case it already exists.

---

src/nupic/algorithms/TemporalMemory.cpp
src/test/unit/algorithms/TemporalMemoryTest.cpp

Fixes #1224
I learned while changing the SparseMatrix that this strategy is much faster.
Hotgym runtime:
**Before:** 2.04 seconds
**After:** 0.90 seconds
So yeah, in some situations it's at least twice as fast.

TM Perf: Densify prevActiveCells rather than binary searching

---

src/CMakeLists.txt

This resolves the bug where changes to headers that the SWIG bindings depend on were not causing SWIG to regenerate the bindings C++ files.
fixes #1235
fixes NUP-2318

Regenerate SWIG bindings C++ files if any headers change.

---

CommonCompilerConfig.cmake
src/CMakeLists.txt
src/nupic/algorithms/Cell.hpp
src/nupic/algorithms/Cells4.cpp
src/nupic/algorithms/Cells4.hpp
src/nupic/algorithms/Segment.cpp
src/nupic/algorithms/Segment.hpp
src/test/unit/algorithms/Cells4Test.cpp
src/test/unit/algorithms/SegmentTest.cpp

Fixes #1014.
This PR prevents wrong synapses from being deleted by `Segment::freeNSynapses` when `segment.updateSynapses` invalidates the lists of candidate synapses in `Cells4::adaptSegment`.
NOTE: Once this PR is merged, need to merge nupic PR https://github.com/numenta/nupic/pull/3469 that updates nupic test `tests/integration/nupic/opf/hotgym_regression_test.py`

NUP-2324 When built with -D_GLIBCXX_DEBUG, c++ detects out-of-bounds access to _synapses in Segment::freeNSynapses

---

src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/Connections.hpp
src/nupic/algorithms/TemporalMemory.cpp
src/nupic/algorithms/TemporalMemory.hpp
src/nupic/bindings/algorithms.i
src/test/integration/ConnectionsPerformanceTest.cpp
src/test/integration/ConnectionsPerformanceTest.hpp
src/test/unit/algorithms/ConnectionsTest.cpp

Fixes #1254
Also add `mapSegmentsToCells` to take advantage of this.
Also remove `getMatchingCells`, which doesn't need to exist.

Change segments to UInt32 to speed up the bindings

---

src/examples/prototest.cpp

@vitaly-krugl - This fixes the bug I mentioned to you and gives a better timing comparison. It doesn't work for the SWIG-related stuff though.

Avoid time conversions that introduce rounding error

---

src/nupic/py_support/PyCapnp.hpp
src/nupic/regions/PyRegion.cpp

Fixes #1290
Please review
I wasn't able to eliminate the number of copies using the existing capnproto API, but was at least able to reduce the number of simultaneously-present copies to limit the impact on the memory footprint.
cc @scottpurdy

NUP-2425 Reduced the number of simultaneously-present copies of py region serialization in PyRegion.cpp

---

src/nupic/py_support/PyHelpers.cpp
src/test/unit/py_support/PyHelpersTest.cpp

Fixes #1294 
See the description in the issue.
Thanks @oxtopus for finding that this segfault often happens shortly after a time when we call `setParameter` with a `bool`.

Stop messing up the refcount on Py_True and Py_False

---

src/nupic/algorithms/Connections.cpp
src/nupic/algorithms/Connections.hpp
src/nupic/algorithms/TemporalMemory.cpp
src/nupic/algorithms/TemporalMemory.hpp
src/nupic/proto/ConnectionsProto.capnp
src/nupic/proto/TemporalMemoryProto.capnp
src/test/integration/ConnectionsPerformanceTest.cpp
src/test/unit/algorithms/ConnectionsTest.cpp
src/test/unit/algorithms/TemporalMemoryTest.cpp

Fixes #986
This change removes `maxSegmentsPerCell` and `maxSynapsesPerSegment` parameters from the `Connections` class, and adds their logic to the `TemporalMemory`. In this new code I fixed the synapse destroy bug mentioned in the issue above.
This change is ~performance neutral. If anything, it's slightly faster.
I've wanted to make this change for a long time. Code that enforces segment/synapse limits is algorithm code, not data structure code. There's no obvious right way to do it, and different algorithms should choose whether/how to handle it explicitly.

Move segment/synapse cleanup out of Connections

---

external/CapnProto.cmake
src/CMakeLists.txt

Installs capnp binaries when given `-DNUPIC_BUILD_PYEXT_MODULES=OFF` so that they may be used downstream.

NUP-2439 Install capnp binaries

---

src/CMakeLists.txt
src/nupic/bindings/algorithms.i
src/nupic/bindings/engine_internal.i
src/nupic/bindings/math.i
src/nupic/py_support/NumpyArrayObject.cpp
src/nupic/py_support/NumpyArrayObject.hpp
src/nupic/py_support/NumpyVector.cpp
src/nupic/py_support/NumpyVector.hpp
src/nupic/py_support/PyArray.cpp
src/nupic/regions/PyRegion.cpp
src/test/integration/PyRegionTest.cpp

Fixes #1331
See the description in the issue.
This populates the `PyArray_API` array with function pointers, allowing C code in `algorithms.so` to run numpy APIs like `PyArray_EquivTypenums`. Without this line, any calls to these APIs will segfault.

Initialize numpy API in "algorithms" module

---

src/nupic/algorithms/SDRClassifier.cpp
src/nupic/algorithms/SDRClassifier.hpp
src/nupic/bindings/algorithms.i
src/test/unit/algorithms/SDRClassifierTest.cpp

Fixes: https://github.com/numenta/nupic.core/issues/1340
Implement the SDR classifier change as in https://github.com/numenta/nupic/pull/3669
Allows SDR classifier to handle multiple categories with a single compute call
@scottpurdy Please review.

Allow SDR classifier to handle multiple category

---

src/nupic/algorithms/ClassifierResult.cpp
src/nupic/algorithms/SDRClassifier.cpp

This is to address a community reported segfault by making it clear that you cannot reuse ClassificationResult instances across calls to SDRClassifier.compute. I looked into having `compute` simply return a new ClassifierResult but it looked like a major refactoring and I wasn't sure I was doing the right thing so punting on that for now.
@mrcslws please review
@ywcui1990 fyi

Give clear exception when clients try to reuse ClassiferResults

---

src/nupic/bindings/algorithms.i

@scottpurdy @rhyolight 
Fixes: https://github.com/numenta/nupic.core/issues/1347
This bug was introduced when I allowed SDR classifier to handle multiple categories with a single compute call.

fix missing actValue bug in SDR classifier

---

src/nupic/bindings/algorithms.i
src/nupic/py_support/NumpyVector.hpp

Fixes #1380 
The `swig` interface now validates the `numpy.array` type making sure it matches the C++ implementation (`nupic::UInt`).  It will now throw an exception when the `compute` method is called with the wrong data type.

 Issue #1380: Validate python parameters passed to SP compute method

---

src/nupic/algorithms/SpatialPooler.cpp
src/test/unit/algorithms/SpatialPoolerTest.cpp

Fixes #1390 
This PR Adds an extra validation to SP global inhibition parameters. It will throw an exception if requesting a global sparsity that cannot be calculated using the available columns.

NUP-2491: Validate global inhibition parameters

---

src/test/unit/algorithms/SpatialPoolerTest.cpp

Closes #1386 
Add simple test to validate SP initialized directly from the constructor vs SP initialized via `initialize()` method

NUP-2492: Add constructor vs initialize test regarding Issue #1386

---

.gitignore
CMakeLists.txt
bindings/py/src/nupic/bindings/regions/PyRegion.py
bindings/py/tests/sparse_link_test.py
external/CMakeLists.txt
src/NupicLibraryUtils.cmake
src/nupic/engine/Input.cpp
src/nupic/engine/Input.hpp
src/nupic/engine/Link.cpp
src/nupic/engine/Output.cpp
src/nupic/engine/Output.hpp
src/nupic/engine/Region.cpp
src/nupic/engine/Spec.cpp
src/nupic/engine/Spec.hpp
src/nupic/ntypes/ArrayBase.cpp
src/nupic/ntypes/ArrayBase.hpp
src/nupic/regions/PyRegion.cpp

The current network API implementation expects the data exchanged between regions to be dense arrays.
This PR extends the network API by allowing regions to use both sparse or dense arrays as their inputs and outputs. Only when necessary the network API will convert the sparse arrays into dense arrays, and vice-versa.
To use this feature, you must first specify which inputs/outputs are sparse using the new `sparse` attribute in the region spec and on the region's `compute` method, use `PyRegion.setSparseOutput` method to update the sparse output. See `bindings/py/tests/sparse_link_test.py`
@subutai, @scottpurdy please review

DEVOPS-353: Add SDR links to the Network API

---

appveyor.yml

Windows 32 is not supported by nupic. I will update bamboo once this PR is merged
@rhyolight Please review

NUP-2505: Remove win32 build from CI

---

src/nupic/algorithms/SDRClassifier.hpp

This error occur
```
nupic.core/src/nupic/algorithms/SDRClassifier.hpp:45:9: error: 'cla_classifier' does not name a type
typedef cla_classifier::ClassifierResult ClassifierResult;
^
```
It is necessary to insert `#include <nupic/algorithms/ClassifierResult.hpp>` into SDRClassifier.hpp

Fix not include ClassifierResult.hpp error

---

src/nupic/engine/Output.cpp
src/nupic/engine/Output.hpp

https://stackoverflow.com/questions/42976461/exception-in-destructor-c
We locally allow throwing an exception from the ~Output destructor.
Fixes: #1000 #1414
Replaces: #1415

Output: fix for gcc 4.7 / c++11 destructor noexcept(true)

---

src/CMakeLists.txt
src/nupic/math/ArrayAlgo.hpp

Fix build error on arm64 Linux
